# Generated by Django 5.2.8 on 2025-12-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityhistory',
            name='note',
        ),
        migrations.AlterField(
            model_name='activityhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
